### ISSUE TITLE
Allow the Fast, Medium and Slow presets to disable the automatic image grid (tiling)

### ISSUE THREAD

**Issue by 0xC0000054** [0xC0000054/pdn-avif#25]
Firefox's AVIF decoder has a longstanding [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1696090) with not supporting AVIF image that use an image grid. An image grid is a sequence of smaller images (tiles) that the decoder combines to reconstruct the full image.

This plugin uses an image grid when saving at the Fast, Medium and Slow presets to keep AOM's encoding time and memory usage at a reasonable level, see #3 for the background on this decision.
The plugin currently uses the following values for the maximum image grid tile size at each preset, if a valid tile size is not found, the image will be will encoded as a single tile.

| Encoder Preset| Max Tile Size |
------------|----------------
| Fast      | 512           |
| Medium    | 1280          |
| Slow      | 1920          |
| Very Slow | N/A           |

Currently the only workaround for compatibility with Firefox is to save the image using the Very Slow preset. This is probelematic because Very Slow also instructs AOM to use its slowest compression mode.

My proposal to fix this issue would be to add a checkbox to the plugin save UI that disables the automatic tiling for those presets when unchecked (or checked?). I am not sure what to call it,  `Use Image Grid` or `Tile Image` may be too technical, and `Firefox compatibility` is specific to a bug in one AVIF implementation.
The checkbox may also need a footnote explaining what it does.

Related to:

https://forums.getpaint.net/topic/124627-some-avifs-cannot-be-opened-in-firefox/
#23
#24

**Comment by rickbrew** [comment]
Personally I'm not a fan of adding options to work around bugs in other applications.

It seems like this significantly degrades the user experience because it prevents cancellation and progress reporting, so it probably shouldn't be worded in a way that potentially makes it enticing, e.g. "[x] Improved compression" (Does disabling tiling improve compression?)

I'm not sure there's a good way to succinctly phrase this checkbox in a user-friendly manner, so using a technical and accurate description may be the best route. Especially if it's something you can get more information on with a web search. Perhaps "[x] Enable tiling (recommended)" or "[x] Enable tiled encoding" and have it greyed out when Very Slow is chosen?

"AVIF tiled encoding" at least points someone down what looks like the right path when you search for it:
<img width="658" alt="image" src="https://github.com/0xC0000054/pdn-avif/assets/10873410/e8dd6aaf-018b-4b1d-8297-1972d42e7529">

**Comment by 0xC0000054** [comment]
> Personally I'm not a fan of adding options to work around bugs in other applications.

I agree. The degraded user experience is also a mark against this change.
Even if I added this option, tiled images would still be the plugin's default behavior. So it would not solve the Firefox compatibility issue unless the user opted-out of tiling, which can already be done with the Very Slow preset.

As far as I know, Firefox is one of the few browsers with this bug. A comment on that bug report indicates that Safari  has the same issue (or at least some versions of it do).

**Comment by rickbrew** [comment]
It's also completely non-obvious that you'd use that checkbox to work around the Firefox issue.

My recommendation would be that if you can't find another reason to include the checkbox, then don't. Firefox needs to fix their bug(s). AVIF is a relatively new and high-profile format, folks are excited about it, there should be someone willing to go in and do this -- we're not talking about some bit-rotted code for handling TIFFs or DIBs that nobody understands anymore because it was written on punch cards

**Comment by 0xC0000054** [comment]
I don't have any other reason for adding the checkbox other than this Firefox bug. Mozilla has had that bug open for almost 4 years, I can only hope that they will eventually address it.
Adobe has not added native AVIF support to Photoshop, and they likely have way more resources than Mozilla does. When I wrote my Photoshop AVIF format plugin, I had no idea that people would still be relying on it nearly 4 years later.

I already recommended the use of libavif's CLI encoder in https://github.com/0xC0000054/pdn-avif/issues/24#issuecomment-1928684185. If people need to work around that Firefox bug they can save as PNG and use that tool to convert the image to AVIF, or use this plugin on Very Slow.
