### ISSUE TITLE
Plugin requires Core 7 - why?

### ISSUE THREAD

**Issue by LexaGV** [0xC0000054/pdn-avif#26]
I have Paint.NET 4.3.7, which is built against Core 6.0; AVIF plugin, bundled w Paint.NET was smth like 1.1.14 and it was working.
I downloaded latest plugin v1.1.31 and... boom! Nothing works, because it's built against Core 7.0; Why?
Is it possible to make one more release, but for Core 6.0? (please)

Just my guess: Pain.NET 5.* is built against Core 7.0, but I cannot use it, bc I use Windows 7 (where Paint 5 doesn't work). What is strange, bc I have VS2022 and two Core versions: 6.0 & 7.0 (to develop apps).

Anyway it could be nice to have plugin for Core 6.0 (or at least some instruction how to build).

Thanks!

**Comment by 0xC0000054** [comment]
This plugin is bundled with paint.net, so it targets the .NET runtime used by the current PDN version at the time each plugin is released. No support is provided for older versions of Paint.NET or the plugin. The last version to work on 4.3.X was 1.1.20, bundled with paint.net 4.3.12.

The build instructions are in the readme, but it probably will not compile on .NET 6.0 due to the code having been updated to use .NET 7.0 features.
